use_frameworks!

platform :ios, '10.0'

target 'ZLAutoHeightTextView_Example' do
  pod 'ZLAutoHeightTextView', :path => '../'

  target 'ZLAutoHeightTextView_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
